import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";
import Head from 'next/head';

import { TRPCReactProvider } from "~/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Delta" />
        <link rel="shortcut icon" href="/favicon.svg" type="image/x-icon" />
        <title>Delta</title>
        <meta property="og:title" content="Delta" />
        <meta property="og:image" content="/favicon.svg" />
        <meta property="og:url" content="https://snucdelta.tech" />
        <meta property="og:type" content="website" />
      </head>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider headers={headers()}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
